language: go

sudo: required

go:
  - 1.7.x

before_install:
  - echo "before_install step"
  - lsb_release -a
  - which go
  - whereis go
  - go version
  - go env
  - env
  - pwd

install:
  - echo "install step"
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install --yes nodejs build-essential
  - sudo npm install -g apidoc@">=0.16.0 <0.17.0"
  - which apidoc
  - whereis apidoc
  - apidoc -v
  - go get -u github.com/kardianos/govendor
  - govendor --version || true
  - go get -u github.com/alecthomas/gometalinter
  - govendor sync -v
  - gometalinter --install --update --force
  - chmod +x doc/godoc/save.sh

before_script:
  - echo "before_script step"
  - make test

script:
  - echo "script step"
  - ([ -n "${TRAVIS_TAG}" ] && make release TAG=${TRAVIS_TAG}) || true

deploy:
  provider: releases
  api_key:
    secure: gpqOYCJuzMXZtUWvxpk6BMJlLJczGk6q0tfRQ1tf31W403KuYVWIR8dhrjMtElHWoE2lvjpMNPMlhshiwofxQHnyeOOv1qxLYsGLglQO/u1If6tQsmtkkoJC8uRqauIYCo8OYXTkOpztBGxiDGNo2Uyl0oK8kMlbN3N76U64U+9B0L1W3YHa7HCtrHdHhRhE92VORkjqjccwzL3961azHreyNat96j6ZrvS+Xrl+lXKrxOVOUEa62cixf2Oea6dM4TfmkvUs4AR4tGpJsfGc/anXBfngnV9khe/H3/dngMyen0W9Hs4NIgGUBHYVEYi5OhDdQm36UhMSyxvMcHyT4CCyjIqrEmTAqoBl8Vm4xsbQVDQ4JzK3adtcrEYspmhXl1aMGMxgKYevjUBGe/XPpGdmmVk+fakL1VGPgJDbuEpEnJZlawHcRKv/mlNm63xysGmEjDgTqf6Ts88Ss7oO1Qzk25QRR5EfyXIIkiyPxi3KIojupI9s2CvCQ2VhyzpVrtY1VyqCZgjG5497aPBnn5piD/isgupsGmLqUTA9lS0WhoA9pq7lYvc94manHykiHjl57eOVqRCEfRFdC8e3Y2KxXvF6I2B0+mfjR/1RCoFvVD+gTpa4zbR+yGKwrLbJgh5+iZVqy354DS5/sYjVfWxMp+s2k69gYZDek6YrZkw=
  file:
    - "./release/nebulo-full-${TRAVIS_TAG}.zip"
    - "./release/nebulo-full-${TRAVIS_TAG}.tar.gz"
    - "./release/nebulo-doc-${TRAVIS_TAG}.zip"
    - "./release/nebulo-doc-${TRAVIS_TAG}.tar.gz"
    - "./release/nebulo-bin-${TRAVIS_TAG}.zip"
    - "./release/nebulo-bin-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
