language: go

sudo: required

go:
  - 1.7.x

env:
  global:
    secure: a9/XUeUzNTB8GzVi5Y2We8H+5kpYofetbuYFsAHPq78RuwSM+MlQoVPOF9ox0y8SFcBrVNOuK9vFaTKAYJ9Cl8jaTywiPaMFmMw8+FdTZeAfKuOiPT2h2m1ozJ4o+Gqfk7r93kAgMpvHBaDfDFxR3ls2hoCWs8T9WVsgE1CMe992GO4Ba8wrsghZresdAdIHXJtM+TA5Nx++9x4DcgPH4EVXYXVRb33dH4TfGx4YiBj2nS4ayGmKCD/fVfasDa8wCMDWp9KAWQmHOHUYLJYoAuNH+VfoR59iCUrpRqGA8EsjZKldDPlg2a+pqP21rbHekvAbIQ5kfHVgHrSQWRfDBYhZ6Z3cvhu0sfv4MvA+leLpEGBSs6v2y7qker0U2uR3nBzbUskJYFuGWh3Wt0GndAeYppdUv2Yy/kw98Dfi0Vs3b/RLM0KhId+oNWtmzhUQI+/c0mOte3bYa9EH1WHZfNE6H5PEZBrKN27BbHzelLBgb8D297fmN1HXvisw10ZZGoA3DSkF13kb1xx6vyDy56/QEHU+iyodw6g+gwYMrT8g5uAVJ3PUxRLJPgw+rIzx+hjz0XH0kzirejGq86/S7kjPoVSsdC1GFZwCfsKB/+f7B2+TCyirBZAsYqblGFO2F106YZwLwbG8vo0JtQaeHEMcjbQ8F4rxA9OgPhOFMKs=

before_install:
  - echo "before_install step"
  - lsb_release -a
  - which go
  - whereis go
  - go version
  - go env
  - env
  - pwd

install:
  - echo "install step"
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install --yes nodejs build-essential
  - sudo npm install -g apidoc@">=0.16.0 <0.17.0"
  - which apidoc
  - whereis apidoc
  - apidoc -v
  - go get -u github.com/kardianos/govendor
  - govendor --version || true
  - go get -u github.com/alecthomas/gometalinter
  - govendor sync -v
  - gometalinter --install --update --force
  - go get github.com/mattn/goveralls

script:
  - echo "script step"
  - ([ -n "${TRAVIS_TAG}" ] && make release TAG=${TRAVIS_TAG}) || make test
  - make coverage
  - goveralls -coverprofile=coverage/coverage.out -service=travis-ci

deploy:
  provider: releases
  api_key:
    secure: gpqOYCJuzMXZtUWvxpk6BMJlLJczGk6q0tfRQ1tf31W403KuYVWIR8dhrjMtElHWoE2lvjpMNPMlhshiwofxQHnyeOOv1qxLYsGLglQO/u1If6tQsmtkkoJC8uRqauIYCo8OYXTkOpztBGxiDGNo2Uyl0oK8kMlbN3N76U64U+9B0L1W3YHa7HCtrHdHhRhE92VORkjqjccwzL3961azHreyNat96j6ZrvS+Xrl+lXKrxOVOUEa62cixf2Oea6dM4TfmkvUs4AR4tGpJsfGc/anXBfngnV9khe/H3/dngMyen0W9Hs4NIgGUBHYVEYi5OhDdQm36UhMSyxvMcHyT4CCyjIqrEmTAqoBl8Vm4xsbQVDQ4JzK3adtcrEYspmhXl1aMGMxgKYevjUBGe/XPpGdmmVk+fakL1VGPgJDbuEpEnJZlawHcRKv/mlNm63xysGmEjDgTqf6Ts88Ss7oO1Qzk25QRR5EfyXIIkiyPxi3KIojupI9s2CvCQ2VhyzpVrtY1VyqCZgjG5497aPBnn5piD/isgupsGmLqUTA9lS0WhoA9pq7lYvc94manHykiHjl57eOVqRCEfRFdC8e3Y2KxXvF6I2B0+mfjR/1RCoFvVD+gTpa4zbR+yGKwrLbJgh5+iZVqy354DS5/sYjVfWxMp+s2k69gYZDek6YrZkw=
  skip_cleanup: true
  file_glob: true
  file:
    - "./release/nebulo-*-${TRAVIS_TAG}*.tar.gz"
  on:
    tags: true
