language: go

go:
  - 1.8.x

env:
  global:
    secure: Tq0S+RXxjgKX2Iv5c3/v0uH43X55ZFvuluXAxh8MnpmMwRy346oYqwq5PdvTTh0AXN1/7cM5g0+LDyQ7YBHzeIE4C222lNDap9OxqsbD/GUrB9gOj8h0aEopziyb6dx9YTwi+Rw7DCsQHH7czXKGdDkYqSweRnQ/Cvy7xcSHoLXQFufyaaziLacvHUgRyTTTs+4DJk5ZwNGXSkShVpLWQU/PVtCZFCGvY8/YLWqL7jr7Ph7XRSeGSZqZSJ2XDJ8PezwfY2FHyxgKdn3Q0dLXIcgdWG4Yy6ZEhnY+QROiqxOFt1QnJLDBJUuo/NruKFv8+7+GTR4shfzqEB8FDQRLOrCAmz2379ARcbbGvDXGK3imPOpd5tcAYSGiyfq/byE/K8Aedq8Zq5Trb4Tf6M4yOqwSjulFo2dKscYQQC+15F9Xii1oEV3E3V2ncoHfIdM5MyLaeQPa/G5xQYDeEX7ssiMkst21d1XPBr/PgnAG2WxjOQVtFZh3E6i5NnXw68XNeX0WjRWwyr3CMFOa0nADdhhHVPfDw++AOwoR+eElsZEoCX16zKnpmvT0hw36P2GH+mHNZZv06djN/ekEFUy3bMAIMoHfTWlb4Kxu5PybkCWvM25YG3lf0D1kHfOHrHnKQ6RV+cqRtav1jmqMg9tpg5mTID3OMMtauLtHEwhKRVE=

install:
  - go get github.com/twitchtv/retool
  - make vendor

script:
  - ([ -n "${TRAVIS_TAG}" ] && make release CI=1 TAG=${TRAVIS_TAG}) || make test CI=1
  - make coverage CI=1
  - retool do goveralls -coverprofile=coverage/coverage.out -service=travis-ci

deploy:
  provider: releases
  api_key:
    secure: gpqOYCJuzMXZtUWvxpk6BMJlLJczGk6q0tfRQ1tf31W403KuYVWIR8dhrjMtElHWoE2lvjpMNPMlhshiwofxQHnyeOOv1qxLYsGLglQO/u1If6tQsmtkkoJC8uRqauIYCo8OYXTkOpztBGxiDGNo2Uyl0oK8kMlbN3N76U64U+9B0L1W3YHa7HCtrHdHhRhE92VORkjqjccwzL3961azHreyNat96j6ZrvS+Xrl+lXKrxOVOUEa62cixf2Oea6dM4TfmkvUs4AR4tGpJsfGc/anXBfngnV9khe/H3/dngMyen0W9Hs4NIgGUBHYVEYi5OhDdQm36UhMSyxvMcHyT4CCyjIqrEmTAqoBl8Vm4xsbQVDQ4JzK3adtcrEYspmhXl1aMGMxgKYevjUBGe/XPpGdmmVk+fakL1VGPgJDbuEpEnJZlawHcRKv/mlNm63xysGmEjDgTqf6Ts88Ss7oO1Qzk25QRR5EfyXIIkiyPxi3KIojupI9s2CvCQ2VhyzpVrtY1VyqCZgjG5497aPBnn5piD/isgupsGmLqUTA9lS0WhoA9pq7lYvc94manHykiHjl57eOVqRCEfRFdC8e3Y2KxXvF6I2B0+mfjR/1RCoFvVD+gTpa4zbR+yGKwrLbJgh5+iZVqy354DS5/sYjVfWxMp+s2k69gYZDek6YrZkw=
  skip_cleanup: true
  file_glob: true
  file:
    - "./release/nebulo-*-${TRAVIS_TAG}*.tar.gz"
  on:
    tags: true
